services:
  - type: web
    name: feira-dia-d
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn feira_site:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0